import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import dotenvFlow from "dotenv-flow";

export const DEFAULT_BASE_URL = "https://lobste.rs";
export const DEFAULT_TIMEOUT_MS = 15_000;

const ENV_BASE_URL_KEY = "CHOWDA_BASE_URL";
const ENV_TIMEOUT_MS_KEY = "CHOWDA_TIMEOUT_MS";

const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const ENV_PATH = resolve(PACKAGE_ROOT, ".env");
export const ENV_LOCAL_PATH = resolve(PACKAGE_ROOT, ".env.local");

export type CliRuntimeConfig = {
  baseUrl: string;
  timeoutMs: number;
};

function normalizeBaseUrlValue(value: string): string {
  return String(value).trim().replace(/\/$/, "");
}

function parseTimeoutMs(value: string | undefined): number {
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed < 1) {
    return DEFAULT_TIMEOUT_MS;
  }
  return parsed;
}

export function loadEnvFilesIntoProcessEnv(): void {
  dotenvFlow.config({
    path: PACKAGE_ROOT,
    node_env: process.env.NODE_ENV,
    silent: true,
    purge_dotenv: false
  });
}

export function resolveRuntimeConfig(): CliRuntimeConfig {
  return {
    baseUrl: normalizeBaseUrlValue(process.env[ENV_BASE_URL_KEY] ?? DEFAULT_BASE_URL),
    timeoutMs: parseTimeoutMs(process.env[ENV_TIMEOUT_MS_KEY])
  };
}

export function writeEnvLocal(config: CliRuntimeConfig): void {
  const baseUrl = normalizeBaseUrlValue(config.baseUrl);
  const timeoutMs = parseTimeoutMs(String(config.timeoutMs));

  const content = [
    "# chowda CLI local overrides",
    "# .env.local values override .env when present",
    "# generated by: pnpm --silent cli setup",
    `${ENV_BASE_URL_KEY}=${baseUrl}`,
    `${ENV_TIMEOUT_MS_KEY}=${timeoutMs}`,
    ""
  ].join("\n");

  writeFileSync(ENV_LOCAL_PATH, content, "utf8");
}
